/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Archivos;
import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.Archivo;

/**
 *
 * @author Johnney
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    public static int n_lines = 0;

    //FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos js,class y py ", "js", "py", "class", "java");
    JFileChooser seleccionar_proyecto = new JFileChooser();

    File carpeta_proyecto;

    Archivos con_archivos;

    Collection<File> archivos;

    ArrayList<Archivo> lista_archivo = new ArrayList<Archivo>();

    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_lenguaje_proyecto = new javax.swing.JLabel();
        jcbx_lenguaje_proyecto = new javax.swing.JComboBox<>();
        btn_seleccionar_proj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mostrar_archivos = new javax.swing.JTable();
        lbl_total_archivos = new javax.swing.JLabel();
        jtf_total_archivos = new javax.swing.JTextField();
        btn_calcular = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_mostrar_lineas_cod = new javax.swing.JTable();
        lbl_modo_metrica = new javax.swing.JLabel();
        jcbx_modo_metrica = new javax.swing.JComboBox<>();
        lbl_salario_medio = new javax.swing.JLabel();
        jtf_salario = new javax.swing.JTextField();
        btn_reporte = new javax.swing.JButton();
        jtxf_total_numero_lineas = new javax.swing.JTextField();
        lbl_total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_lenguaje_proyecto.setText("Lenguaje del Proyeto:");

        jcbx_lenguaje_proyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proyecto PHP", "Proyecto Java", "Proyecto Node js" }));

        btn_seleccionar_proj.setText("Seleccionar Proyecto");
        btn_seleccionar_proj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionar_projActionPerformed(evt);
            }
        });

        tbl_mostrar_archivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Nombre de la clase", "Lenguaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_mostrar_archivos);
        if (tbl_mostrar_archivos.getColumnModel().getColumnCount() > 0) {
            tbl_mostrar_archivos.getColumnModel().getColumn(0).setMinWidth(30);
            tbl_mostrar_archivos.getColumnModel().getColumn(0).setMaxWidth(30);
            tbl_mostrar_archivos.getColumnModel().getColumn(1).setMinWidth(240);
            tbl_mostrar_archivos.getColumnModel().getColumn(2).setMinWidth(80);
            tbl_mostrar_archivos.getColumnModel().getColumn(2).setMaxWidth(80);
        }

        lbl_total_archivos.setText("Total Archivos:");

        jtf_total_archivos.setEditable(false);

        btn_calcular.setText("Calcular");
        btn_calcular.setEnabled(false);
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        tbl_mostrar_lineas_cod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Nombre de la clase", "Líneas de Código"
            }
        ));
        jScrollPane2.setViewportView(tbl_mostrar_lineas_cod);
        if (tbl_mostrar_lineas_cod.getColumnModel().getColumnCount() > 0) {
            tbl_mostrar_lineas_cod.getColumnModel().getColumn(0).setMinWidth(30);
            tbl_mostrar_lineas_cod.getColumnModel().getColumn(0).setMaxWidth(30);
            tbl_mostrar_lineas_cod.getColumnModel().getColumn(1).setMinWidth(150);
            tbl_mostrar_lineas_cod.getColumnModel().getColumn(2).setMinWidth(120);
            tbl_mostrar_lineas_cod.getColumnModel().getColumn(2).setMaxWidth(120);
        }

        lbl_modo_metrica.setText("Modo Métrica COCOMO2:");

        jcbx_modo_metrica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Orgánico", "Semilibre", "Rígido" }));

        lbl_salario_medio.setText("Salario Mensual:");

        btn_reporte.setText("Ver Reporte");

        lbl_total.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lbl_modo_metrica)
                        .addGap(18, 18, 18)
                        .addComponent(jcbx_modo_metrica, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(lbl_salario_medio)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(btn_reporte))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbl_total_archivos)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtf_total_archivos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_lenguaje_proyecto)
                                        .addGap(39, 39, 39)
                                        .addComponent(jcbx_lenguaje_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_seleccionar_proj, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxf_total_numero_lineas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_lenguaje_proyecto)
                    .addComponent(jcbx_lenguaje_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_seleccionar_proj, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_total_archivos)
                    .addComponent(jtf_total_archivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxf_total_numero_lineas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_total))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_modo_metrica)
                    .addComponent(jcbx_modo_metrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_salario_medio)
                    .addComponent(jtf_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reporte))
                .addGap(233, 233, 233))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seleccionar_projActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionar_projActionPerformed
        String lenguaje = jcbx_lenguaje_proyecto.getSelectedItem().toString();

        seleccionar_proyecto.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        //seleccionar_proyecto.setFileFilter(filter);
        if (seleccionar_proyecto.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION) {

            carpeta_proyecto = seleccionar_proyecto.getSelectedFile();

            archivos = con_archivos.buscarArchivos(carpeta_proyecto, lenguaje);

            if (archivos.isEmpty()) {

                JOptionPane.showMessageDialog(null, "No existen Coincidencias");

            } else {
                for (File archivo : archivos) {

                    Archivo obj_archivo = new Archivo();

                    obj_archivo.setNombre(archivo.getName());
                    obj_archivo.setLenguaje_progamacion(lenguaje);
                    obj_archivo.setRuta(archivo.getAbsolutePath().toString());
                    obj_archivo.setNumero_lineas(0);

                    lista_archivo.add(obj_archivo);

                }
                mostrar_matriz1();
                btn_calcular.setEnabled(true);

            }
        }
    }//GEN-LAST:event_btn_seleccionar_projActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
         String modo_CC = jcbx_modo_metrica.getSelectedItem().toString();
        
        if (!archivos.isEmpty()) {
            for (Archivo a : lista_archivo) {
                int lineas_codigo = con_archivos.calcularLineasCodigo(a);
                a.setNumero_lineas(lineas_codigo);
            }
            mostrar_matriz2();

        }
        
        
    }//GEN-LAST:event_btn_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_reporte;
    private javax.swing.JButton btn_seleccionar_proj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbx_lenguaje_proyecto;
    private javax.swing.JComboBox<String> jcbx_modo_metrica;
    private javax.swing.JTextField jtf_salario;
    private javax.swing.JTextField jtf_total_archivos;
    private javax.swing.JTextField jtxf_total_numero_lineas;
    private javax.swing.JLabel lbl_lenguaje_proyecto;
    private javax.swing.JLabel lbl_modo_metrica;
    private javax.swing.JLabel lbl_salario_medio;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_total_archivos;
    private javax.swing.JTable tbl_mostrar_archivos;
    private javax.swing.JTable tbl_mostrar_lineas_cod;
    // End of variables declaration//GEN-END:variables

    private void mostrar_matriz1() {
        String matriz[][] = new String[lista_archivo.size()][3];

        for (int i = 0; i < lista_archivo.size(); i++) {

            matriz[i][0] = Integer.toString(i + 1);
            matriz[i][1] = lista_archivo.get(i).getNombre();
            matriz[i][2] = lista_archivo.get(i).getLenguaje_progamacion();
        }

        tbl_mostrar_archivos.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "#", "Nombre de la clase", "Lenguaje"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        jtf_total_archivos.setText(Integer.toString(lista_archivo.size()));

    }

    private void mostrar_matriz2() {
        String matriz[][] = new String[lista_archivo.size()][3];
        int total_numero_lineas = 0;

        for (int i = 0; i < lista_archivo.size(); i++) {

            matriz[i][0] = Integer.toString(i + 1);
            matriz[i][1] = lista_archivo.get(i).getNombre();
            matriz[i][2] = Integer.toString(lista_archivo.get(i).getNumero_lineas());

            total_numero_lineas = total_numero_lineas + lista_archivo.get(i).getNumero_lineas();
        }
        
        n_lines = total_numero_lineas;

        tbl_mostrar_lineas_cod.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "#", "Nombre de la clase", "Líneas de Código"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        jtxf_total_numero_lineas.setText(Integer.toString(total_numero_lineas));
        
    }
}
