/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Archivos;
import controlador.Reportes;
import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import modelo.Archivo;

/**
 *
 * @author Johnney
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    public static int n_lines = 0;

    public static double factor_ajuste = 1.0;

    //FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos js,class y py ", "js", "py", "class", "java");
    JFileChooser seleccionar_proyecto = new JFileChooser();

    public static File carpeta_proyecto;

    Archivos con_archivos;

    Reportes con_reportes;

    Collection<File> archivos;

    ArrayList<Archivo> lista_archivo = new ArrayList<Archivo>();

    public static ArrayList<Integer> atributos = new ArrayList<>();

    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_titulo = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_subtitulo = new javax.swing.JLabel();
        pnl_cuerpo = new javax.swing.JPanel();
        jcbx_lenguaje_proyecto = new javax.swing.JComboBox<>();
        lbl_lenguaje_proyecto = new javax.swing.JLabel();
        btn_seleccionar_proj = new rsbuttoncustom.RSButtonCustom();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_mostrar_archivos = new rojerusan.RSTableMetro();
        lbl_total_archivos = new javax.swing.JLabel();
        jtf_total_archivos = new javax.swing.JTextField();
        btn_calcular = new rsbuttoncustom.RSButtonCustom();
        btn_refrescar = new rsbuttoncustom.RSButtonCustom();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mostrar_lineas_cod = new rojerusan.RSTableMetro();
        jtxf_total_numero_lineas = new javax.swing.JTextField();
        lbl_total = new javax.swing.JLabel();
        lbl_modo_metrica = new javax.swing.JLabel();
        jtf_modo_metrica = new javax.swing.JTextField();
        jtf_salario = new javax.swing.JTextField();
        lbl_salario_medio = new javax.swing.JLabel();
        btn_factor_ajuste = new rsbuttoncustom.RSButtonCustom();
        btn_reporte = new rsbuttoncustom.RSButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Métricas código fuente (Líneas de Código)");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(965, 700));
        setMinimumSize(new java.awt.Dimension(965, 700));
        setPreferredSize(new java.awt.Dimension(965, 700));
        setResizable(false);

        pnl_titulo.setBackground(new java.awt.Color(246, 149, 7));
        pnl_titulo.setMaximumSize(new java.awt.Dimension(965, 150));
        pnl_titulo.setMinimumSize(new java.awt.Dimension(965, 150));
        pnl_titulo.setPreferredSize(new java.awt.Dimension(965, 150));

        lbl_titulo.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("MÉTRICAS CÓDIGO FUENTE");

        lbl_subtitulo.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        lbl_subtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_subtitulo.setText("COCOMO II");

        javax.swing.GroupLayout pnl_tituloLayout = new javax.swing.GroupLayout(pnl_titulo);
        pnl_titulo.setLayout(pnl_tituloLayout);
        pnl_tituloLayout.setHorizontalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tituloLayout.createSequentialGroup()
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tituloLayout.createSequentialGroup()
                        .addComponent(lbl_subtitulo)
                        .addGap(410, 410, 410))))
        );
        pnl_tituloLayout.setVerticalGroup(
            pnl_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tituloLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_subtitulo)
                .addGap(532, 532, 532))
        );

        lbl_subtitulo.getAccessibleContext().setAccessibleName("lbl_subtitulo");

        pnl_cuerpo.setBackground(new java.awt.Color(45, 60, 80));
        pnl_cuerpo.setMaximumSize(new java.awt.Dimension(965, 540));
        pnl_cuerpo.setMinimumSize(new java.awt.Dimension(965, 540));
        pnl_cuerpo.setPreferredSize(new java.awt.Dimension(965, 540));

        jcbx_lenguaje_proyecto.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jcbx_lenguaje_proyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proyecto PHP", "Proyecto Java", "Proyecto Node js" }));

        lbl_lenguaje_proyecto.setBackground(new java.awt.Color(255, 255, 255));
        lbl_lenguaje_proyecto.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbl_lenguaje_proyecto.setForeground(new java.awt.Color(255, 255, 255));
        lbl_lenguaje_proyecto.setText("Lenguaje del Proyeto:");

        btn_seleccionar_proj.setBackground(new java.awt.Color(45, 60, 80));
        btn_seleccionar_proj.setForeground(new java.awt.Color(255, 255, 255));
        btn_seleccionar_proj.setText("Seleccionar Proyecto");
        btn_seleccionar_proj.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        btn_seleccionar_proj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionar_projActionPerformed(evt);
            }
        });

        tbl_mostrar_archivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Nombre de la Clase", "Lenguaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_mostrar_archivos.setColorBackgoundHead(new java.awt.Color(246, 149, 7));
        tbl_mostrar_archivos.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_mostrar_archivos.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_mostrar_archivos.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_mostrar_archivos.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        tbl_mostrar_archivos.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        tbl_mostrar_archivos.setFuenteFilas(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        tbl_mostrar_archivos.setFuenteFilasSelect(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        tbl_mostrar_archivos.setFuenteHead(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        tbl_mostrar_archivos.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(tbl_mostrar_archivos);
        if (tbl_mostrar_archivos.getColumnModel().getColumnCount() > 0) {
            tbl_mostrar_archivos.getColumnModel().getColumn(0).setMinWidth(30);
            tbl_mostrar_archivos.getColumnModel().getColumn(0).setMaxWidth(30);
            tbl_mostrar_archivos.getColumnModel().getColumn(1).setMinWidth(150);
            tbl_mostrar_archivos.getColumnModel().getColumn(2).setMinWidth(120);
            tbl_mostrar_archivos.getColumnModel().getColumn(2).setMaxWidth(120);
        }

        lbl_total_archivos.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbl_total_archivos.setForeground(new java.awt.Color(255, 255, 255));
        lbl_total_archivos.setText("Total Archivos:");

        jtf_total_archivos.setEditable(false);

        btn_calcular.setBackground(new java.awt.Color(45, 60, 80));
        btn_calcular.setForeground(new java.awt.Color(255, 255, 255));
        btn_calcular.setText("Calcular");
        btn_calcular.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        btn_refrescar.setBackground(new java.awt.Color(45, 60, 80));
        btn_refrescar.setForeground(new java.awt.Color(255, 255, 255));
        btn_refrescar.setText("Limpiar");
        btn_refrescar.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        btn_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refrescarActionPerformed(evt);
            }
        });

        tbl_mostrar_lineas_cod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Nombre de la Clase", "Líneas de Código"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_mostrar_lineas_cod.setColorBackgoundHead(new java.awt.Color(246, 149, 7));
        tbl_mostrar_lineas_cod.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_mostrar_lineas_cod.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tbl_mostrar_lineas_cod.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tbl_mostrar_lineas_cod.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        tbl_mostrar_lineas_cod.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        tbl_mostrar_lineas_cod.setFuenteFilas(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        tbl_mostrar_lineas_cod.setFuenteFilasSelect(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        tbl_mostrar_lineas_cod.setFuenteHead(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        tbl_mostrar_lineas_cod.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tbl_mostrar_lineas_cod);
        if (tbl_mostrar_lineas_cod.getColumnModel().getColumnCount() > 0) {
            tbl_mostrar_lineas_cod.getColumnModel().getColumn(0).setMinWidth(30);
            tbl_mostrar_lineas_cod.getColumnModel().getColumn(0).setMaxWidth(30);
            tbl_mostrar_lineas_cod.getColumnModel().getColumn(1).setMinWidth(140);
            tbl_mostrar_lineas_cod.getColumnModel().getColumn(2).setMinWidth(130);
            tbl_mostrar_lineas_cod.getColumnModel().getColumn(2).setMaxWidth(130);
        }

        lbl_total.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(255, 255, 255));
        lbl_total.setText("Total Líneas:");

        lbl_modo_metrica.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbl_modo_metrica.setForeground(new java.awt.Color(255, 255, 255));
        lbl_modo_metrica.setText("Modo Métrica COCOMO II:");

        jtf_modo_metrica.setEditable(false);

        lbl_salario_medio.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbl_salario_medio.setForeground(new java.awt.Color(255, 255, 255));
        lbl_salario_medio.setText("Salario Mensual:");

        btn_factor_ajuste.setBackground(new java.awt.Color(45, 60, 80));
        btn_factor_ajuste.setForeground(new java.awt.Color(255, 255, 255));
        btn_factor_ajuste.setText("Factor Ajuste");
        btn_factor_ajuste.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        btn_factor_ajuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_factor_ajusteActionPerformed(evt);
            }
        });

        btn_reporte.setBackground(new java.awt.Color(45, 60, 80));
        btn_reporte.setForeground(new java.awt.Color(255, 255, 255));
        btn_reporte.setText("Ver Reporte");
        btn_reporte.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_cuerpoLayout = new javax.swing.GroupLayout(pnl_cuerpo);
        pnl_cuerpo.setLayout(pnl_cuerpoLayout);
        pnl_cuerpoLayout.setHorizontalGroup(
            pnl_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cuerpoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnl_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_cuerpoLayout.createSequentialGroup()
                        .addComponent(lbl_lenguaje_proyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbx_lenguaje_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_seleccionar_proj, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_cuerpoLayout.createSequentialGroup()
                        .addGroup(pnl_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_cuerpoLayout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(btn_factor_ajuste, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_cuerpoLayout.createSequentialGroup()
                                .addComponent(lbl_modo_metrica)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_modo_metrica, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_total)))
                        .addGap(18, 18, 18)
                        .addComponent(jtxf_total_numero_lineas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_cuerpoLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(pnl_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_cuerpoLayout.createSequentialGroup()
                        .addComponent(lbl_total_archivos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_total_archivos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_cuerpoLayout.createSequentialGroup()
                        .addGroup(pnl_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_cuerpoLayout.createSequentialGroup()
                        .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(btn_refrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_cuerpoLayout.createSequentialGroup()
                        .addComponent(lbl_salario_medio)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(341, 341, 341))))
        );
        pnl_cuerpoLayout.setVerticalGroup(
            pnl_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cuerpoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnl_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_lenguaje_proyecto)
                    .addComponent(jcbx_lenguaje_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_seleccionar_proj, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_total_archivos)
                    .addComponent(jtf_total_archivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(pnl_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_modo_metrica)
                        .addComponent(jtf_modo_metrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_total))
                    .addComponent(jtxf_total_numero_lineas))
                .addGap(18, 18, 18)
                .addGroup(pnl_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_salario_medio)
                    .addComponent(jtf_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_cuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_factor_ajuste, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_cuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_cuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seleccionar_projActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionar_projActionPerformed
        String lenguaje = jcbx_lenguaje_proyecto.getSelectedItem().toString();

        seleccionar_proyecto.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        //seleccionar_proyecto.setFileFilter(filter);
        if (seleccionar_proyecto.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION) {

            carpeta_proyecto = seleccionar_proyecto.getSelectedFile();

            archivos = con_archivos.buscarArchivos(carpeta_proyecto, lenguaje);

            if (archivos.isEmpty()) {

                JOptionPane.showMessageDialog(null, "No existen Coincidencias");

            } else {
                for (File archivo : archivos) {

                    Archivo obj_archivo = new Archivo();

                    obj_archivo.setNombre(archivo.getName());
                    obj_archivo.setLenguaje_progamacion(lenguaje);
                    obj_archivo.setRuta(archivo.getAbsolutePath().toString());
                    obj_archivo.setNumero_lineas(0);

                    lista_archivo.add(obj_archivo);

                }
                mostrar_matriz1();
                btn_calcular.setEnabled(true);

            }
        }
    }//GEN-LAST:event_btn_seleccionar_projActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        if (!archivos.isEmpty()) {
            for (Archivo a : lista_archivo) {
                int lineas_codigo = con_archivos.calcularLineasCodigo(a);
                a.setNumero_lineas(lineas_codigo);
            }
            mostrar_matriz2();

            btn_factor_ajuste.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(null, "Existen 0 archivos a calcuar");
        }
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refrescarActionPerformed
        n_lines = 0;

        factor_ajuste = 1.0;

        archivos = new HashSet<File>();

        lista_archivo = new ArrayList<Archivo>();

        atributos = new ArrayList<Integer>();

        btn_calcular.setEnabled(false);

        jtf_modo_metrica.setText("");

        jtf_salario.setText("");

        jtf_total_archivos.setText("");

        jtxf_total_numero_lineas.setText("");

        eliminarTabla(tbl_mostrar_archivos);

        eliminarTabla(tbl_mostrar_lineas_cod);
    }//GEN-LAST:event_btn_refrescarActionPerformed

    private void btn_factor_ajusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_factor_ajusteActionPerformed
        FactorAjuste fa = new FactorAjuste();

        fa.setVisible(true);
    }//GEN-LAST:event_btn_factor_ajusteActionPerformed

    private void btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteActionPerformed
        String salario = jtf_salario.getText();
        int parse_numero = 0;

        if (salario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un salario");
        } else {
            try {
                parse_numero = Integer.parseInt(salario);
                Reporte reporte = new Reporte();
                reporte.setVisible(true);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un salario válido");
            }
        }
    }//GEN-LAST:event_btn_reporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttoncustom.RSButtonCustom btn_calcular;
    private rsbuttoncustom.RSButtonCustom btn_factor_ajuste;
    private rsbuttoncustom.RSButtonCustom btn_refrescar;
    private rsbuttoncustom.RSButtonCustom btn_reporte;
    private rsbuttoncustom.RSButtonCustom btn_seleccionar_proj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jcbx_lenguaje_proyecto;
    public static javax.swing.JTextField jtf_modo_metrica;
    public static javax.swing.JTextField jtf_salario;
    private javax.swing.JTextField jtf_total_archivos;
    private javax.swing.JTextField jtxf_total_numero_lineas;
    private javax.swing.JLabel lbl_lenguaje_proyecto;
    private javax.swing.JLabel lbl_modo_metrica;
    private javax.swing.JLabel lbl_salario_medio;
    private javax.swing.JLabel lbl_subtitulo;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_total_archivos;
    private javax.swing.JPanel pnl_cuerpo;
    private javax.swing.JPanel pnl_titulo;
    private rojerusan.RSTableMetro tbl_mostrar_archivos;
    private rojerusan.RSTableMetro tbl_mostrar_lineas_cod;
    // End of variables declaration//GEN-END:variables

    private void mostrar_matriz1() {
        String matriz[][] = new String[lista_archivo.size()][3];

        for (int i = 0; i < lista_archivo.size(); i++) {

            matriz[i][0] = Integer.toString(i + 1);
            matriz[i][1] = lista_archivo.get(i).getNombre();
            matriz[i][2] = lista_archivo.get(i).getLenguaje_progamacion();
        }

        tbl_mostrar_archivos.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "#", "Nombre de la clase", "Lenguaje"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        jtf_total_archivos.setText(Integer.toString(lista_archivo.size()));

    }

    private void mostrar_matriz2() {
        String matriz[][] = new String[lista_archivo.size()][3];
        int total_numero_lineas = 0;

        double nkloc = 0.0;

        for (int i = 0; i < lista_archivo.size(); i++) {

            matriz[i][0] = Integer.toString(i + 1);
            matriz[i][1] = lista_archivo.get(i).getNombre();
            matriz[i][2] = Integer.toString(lista_archivo.get(i).getNumero_lineas());

            total_numero_lineas = total_numero_lineas + lista_archivo.get(i).getNumero_lineas();
        }

        n_lines = total_numero_lineas;

        tbl_mostrar_lineas_cod.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "#", "Nombre de la clase", "Líneas de Código"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        jtxf_total_numero_lineas.setText(Integer.toString(total_numero_lineas));

        if (total_numero_lineas > 0) {

            nkloc = con_reportes.kloc(n_lines);

            if (nkloc > 0 && nkloc < 50) {
                jtf_modo_metrica.setText("Organico");
            }
            if (nkloc >= 50 && nkloc < 300) {
                jtf_modo_metrica.setText("Semilibre");
            }

            if (nkloc >= 300) {
                jtf_modo_metrica.setText("Rigido");
            }

        }

    }

    private void eliminarTabla(JTable tabla) {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            for (int j = 0; j < tabla.getColumnCount(); j++) {
                tabla.setValueAt("", i, j);
            }
        }
    }

}
